### ISSUE TITLE
README.md: Healthchecks section needs update

### ISSUE THREAD

**Issue by jx-opher** [indeedeng/status#10]
First paragraph of "Healthchecks" section ends abruptly:
> Healthchecks are pages within applications that take all the dependencies and dump their statuses in a JSON format They can help shed light into services that are currently unavailable or unhealthy. This feature is only available through the status-web package, but sim

**Comment by jpitz** [comment]
I updated the readme. Not sure where I was going with that sentence so I just touched it up. Thanks @jx-opher
