### ISSUE TITLE
Please put the compatible java version in build.grade file

### ISSUE THREAD

**Issue by reinardhz** [indeedeng/status#30]
Our projects are using this library and we want to upgrade this library to higher version. But I can't find the compatible java version in file `build.gradle` or `README.md`. Please add the compatible java version in `build.gradle` file or `README.md`

**Comment by mmorrisontx** [comment]
Not sure when this ticket will be picked up, but all currently published versions of this library are compatible with java 8+.

**Comment by mmorrisontx** [comment]
Closing all issues as this repository is now archived.
