### ISSUE TITLE
Ugrade to com.fasterxml.jackson.core 2.1.2

### ISSUE THREAD

**Issue by camerondavison** [indeedeng/status#4]
Currently status is using org.codehaus.jackson, since this is old and deprecated http://jackson.codehaus.org/ says https://github.com/FasterXML/jackson which says https://github.com/FasterXML/jackson-databind where the maven import code says to use 'com.fasterxml.jackson.core'

**Comment by youknowjack** [comment]
Done is 597df39812f1e695366fd38109157ec49ba5a647
