### ISSUE TITLE
BUG on indeed.com front page appearance when viewing abroad - Needs fixin'

### ISSUE THREAD

**Issue by HAFUCH** [indeedeng/status#7]
Typing indeed.com into address bar in The Netherlands will correctly direct you to indeed.nl. However at the bottom it then state "Voor vacatures in Nederland gaat u naar Indeed Nederland" which means: For jobs in The Netherlands go to Indeed Netherlands.
It should say: For jobs in the USA go to indeed.com (in the whatever local language).

Notes: 
1. This is a text error only as when you click on the link it WILL send you correctly to indeed.com(USA).
2. Had the same issue logging in from Spain and Germany.

![indeed int l error](https://cloud.githubusercontent.com/assets/12855694/8124071/99b06ac4-10d5-11e5-80d3-2936d11e4b43.jpg)

**Comment by ketang** [comment]
Thank you for your bug report.  I have passed this along to the relevant team.  Please note that this issue tracker is for the open source Status library, not for Indeed as a whole.  For issues with the Indeed site, please refer to the Help Center: http://www.indeed.nl/help
