### ISSUE TITLE
system status evaluation rules documentation

### ISSUE THREAD

**Issue by netudima** [indeedeng/status#8]
The following explanation potentially can be added to README (I captured the idea in such way while analyzed how system status evaluation actually works):

Dependency check status is converted to a efficient dependency check status based on Urgency of the correspondent dependency: 

| Status\Urgency | REQUIRED | STRONG | WEAK   | NONE | 
| ----------------- | ----------- | ---------- | -------- | ------- |
| OUTAGE            | OUTAGE   | MAJOR    | MINOR | OK      | 
| MAJOR              | MAJOR     | MAJOR    | MINOR | OK      | 
| MINOR              | MINOR     | MINOR    | MINOR | OK      | 
| OK                     | OK             | OK          | OK        | OK      | 

System status = min(efficient dependency check status)

**Comment by youknowjack** [comment]
I think something like this might be useful in the first paragraph of the README under Dependency Management.

**Comment by jpitz** [comment]
I tweaked the content a little bit and added to the readme. Feel free to take a look at the diff and let me know if there is anything you'd like to have changed.

**Comment by youknowjack** [comment]
Merged in dfdc36989d478b8786e356e011bf5ff5d23d598c
